### PR TITLE
Rule inconsistency fixed for Constant

### PR DESCRIPTION
**Pull request by tolgayildirim**
The decisions we made under the Constant and Extension topics did not match. Constant edited according to the decisions in Extension.

https://gitlab.trendyol.com/mobile/mobile-all/ios-all/shared/iOS/-/merge_requests/9055#note_4668736

### CODE REVIEW

**Review by batuhansk — APPROVED** [review]

**Comment by aniltaskiran** [comment]
Why are we changing this one? Actually, we used a lot of time Private extension while we used Constant enum. I think right now this rule is much more appropriate.

**Comment by tolgayildirim** [comment]
> Why are we changing this one? Actually, we used a lot of time Private extension while we used Constant enum. I think right now this rule is much more appropriate.

@aniltaskiran "Specifying the access control on the declaration itself helps engineers more quickly determine the access control level of an individual declaration."

While deciding on this, we considered that even though there are no changes in the main extension during code reviews, they don't appear in the diff, and we only see the relevant change. To determine whether access control is used correctly or incorrectly in the relevant change, we assigned access control to the responsibility of the related sub-definitions.

**Comment by aniltaskiran** [comment]
> While deciding on this, we considered that even though there are no changes in the main extension during code reviews, they don't appear in the diff, and we only see the relevant change. 

As i know Gitlab is not work like that bro. You can see if you add new line to inside extension, Gitlab shows that to you

CleanShot 2024-08-02 at 12 20 17@2x

**Comment by tolgayildirim** [comment]
> As i know Gitlab is not work like that bro. You can see if you add new line to inside extension, Gitlab shows that to you


Yes, you are right, but do you think every reviewer will pay attention to this?

**Comment by aniltaskiran** [comment]
This one is inside that Constant. Whether this constant is private or not, the reviewer cannot see it. I think if we add private to the constant, we cannot even see it. How can any reviewer see it? With my approach, at least the reviewer can see it.

CleanShot 2024-08-02 at 12 30 08@2x

**Comment by tolgayildirim** [comment]
> This one is inside that Constant. Whether this constant is private or not, the reviewer cannot see it. I think if we add private to the constant, we cannot even see it. How can any reviewer see it? With my approach, at least the reviewer can see it.

I agree with you but let's say you have an extension that conforms to an interface, and the next developer adds a function that should be private, but they add it as internal. How would you know what the access control should be? You would need to check whether it has been added to the interface or not. Actually, your concern is acceptable. However, we made our decision because the approach we chose seemed safer to us.

**Comment by aniltaskiran** [comment]
I did not understand your example because no one can add function beacuse rule about the creation of constant. No one can add function inside of it.

**Comment by tolgayildirim** [comment]
In the file change, there is a reference like this;
https://github.com/Trendyol/ios-guidelines/blob/master/code_style_guideline/code_style_guideline.md#4-extensionaccesscontrol. 

Did you check this? Also, Are you suggesting that we should keep constants separate from this rule?

**Comment by tolgayildirim** [comment]
P.S = This issue will be discussed again next week. We'll merge the decision we made with the team for now.

**Comment by aniltaskiran** [comment]
Yeap i checked that. I think they are different. It should be separate from each others

**Pull request merged**
